server:
  port: 8080

spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/***
    username: *
    password: *

  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.PostgresSQLDialect
    show-sql: false

  main:
    web-application-type: servlet

  mail:
    host: smtp.gmail.com
    port: 587
    username: faculty.electiv.courses@gmail.com
    password: vfsizenwkhheavyw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  api-docs:
    enabled: true
    path: /api-docs