server:
  port: 8080

spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 2003

  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.PostgresSQLDialect
    show-sql: true

  main:
    web-application-type: servlet

  api-docs:
    enabled: true
    path: /api-docs